version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: caronte
    volumes:
      - ./src:/opt/app/caronte/src

    restart: on-failure

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 45s
      timeout: 30s
      retries: 3
      start_period: 45s

    networks:
      - caronte-net

    command: npm run start:dev

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

    networks:
      - caronte-net

    depends_on:
      - node-app

    command: [nginx, "-g", "daemon off;"]

networks:
  caronte-net:
