version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: caronte
    volumes:
      - ./src:/opt/app/caronte/src

    restart: on-failure

    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]
      interval: 45s
      timeout: 30s
      retries: 3
      start_period: 45s

    networks:
      - caronte-net

    depends_on:
      - redis

    command: npm run start

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

    depends_on:
      - node-app

    networks:
      - caronte-net

    command: [nginx, "-g", "daemon off;"]

  redis:
    image: redis
    container_name: redis

    ports:
      - 6379:6379

    networks:
      - caronte-net

networks:
  caronte-net:
